<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EEWTelop.Infrastructure.Wolfx\EEWTelop.Infrastructure.Wolfx.csproj" />
  </ItemGroup>
</Project>
