<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Fixtures\vxse53-large-eruption.xml" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\..\src\EEWTelop.Infrastructure.Axis\EEWTelop.Infrastructure.Axis.csproj" />
    <ProjectReference Include="..\..\src\EEWTelop.Infrastructure.Dmdata\EEWTelop.Infrastructure.Dmdata.csproj" />
  </ItemGroup>
</Project>
